title: Davor Banović | hrvatski pisac i književni prevoditelj, autor Južnih krajeva i prevoditelj SF klasika.
email: davor.banovic@gmail.com
description: >-
  Mrežna stranica Davora Banovića, hrvatskog pisca i književnog prevoditelja s engleskog jezika. 
  Davor je autor romana Južni krajevi, a u svom prevoditeljskom portfelju ima djela Roberta A. 
  Heinleina, H.P. Lovecrafta, Freda Saberhagena... Prijevodi vizionarskih SF klasika, spekulativne 
  fikcije i zahtjevnih publicističkih djela. 
  
 
url: https://davorbanovic.com
image: https://davorbanovic.com/assets/images/back.jpg

timezone: Europe/Zagreb

include:
  - _pages
  - prijevodi

plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-paginate-v2

exclude :
  - cards
  - ducker
  - fretmaster
  - googlee1718026ca119ee1.html
  - modes
  - nailta

defaults:
  - scope:
      path: "" # Primenjuje se na sve datoteke u projektu
      type: "posts" # Odnosi se samo na objave (posts)
    values:
      layout: "post"
      author: "Davor Banović"
      category: ""
      image: ""
      description: "" # Prazno polje koje te podsjeća da ga ispuniš

sass: { style: compressed }

# Postavke za paginaciju bloga i kategorija
pagination:
  enabled: true
  per_page: 4                   # Koliko kartica po stranici
  permalink: '/:num/'      # Putanja za glavnu stranicu (npr. /page/2/)
  title: ':title - Stranica :num'
  limit: 0                     # 0 znači bez limita (svi postovi)


 # Osigurava da se Service Worker i Manifest kopiraju bez izmjena
#include:
#  - mojih1500/sw.js
#  - mojih1500/manifest.json
