title: Davor Banović | hrvatski pisac i književni prevoditelj, autor Južnih krajeva 
email: davor.banovic@gmail.com
description: >-
  Mrežna stranica Davora Banovića, hrvatskog pisca i književnog prevoditelja s engleskog jezika. 
  Prijevodi vizionarskih SF klasika, spekulativne fikcije i zahtjevnih publicističkih djela. 
 
url: https://davorbanovic.com
image: https://davorbanovic.com/assets/images/back.jpg

timezone: Europe/Zagreb

include:
  - _pages
  - prijevodi

plugins:
  - jekyll-sitemap

exclude :
  - cards
  - ducker
  - fretmaster
  - googlee1718026ca119ee1.html
  - modes
  - nailta

defaults:
  - scope:
      path: "" # Primenjuje se na sve datoteke u projektu
      type: "posts" # Odnosi se samo na objave (posts)
    values:
      layout: "post"
      author: "Davor Banović"
      category: ""
      image: ""
      description: "" # Prazno polje koje te podsjeća da ga ispuniš